:repo-name: rsd-engyon-syntax

= Ribose Standard: Secure document -- Engyon -- Plain text representation

This work item belongs to TC CALSPAM.

image:https://travis-ci.com/riboseinc/rsd-engyon-syntax.svg?branch=master["Build Status", link="https://travis-ci.com/riboseinc/rsd-engyon-syntax"]

This document is available in its rendered forms here:

* https://riboseinc.github.io/rsd-engyon-syntax/[Ribose Standard: Secure document -- Engyon -- Plain text representation (HTML)]
* https://riboseinc.github.io/rsd-engyon-syntax/rsd-engyon-syntax.pdf[PDF]
* https://riboseinc.github.io/rsd-engyon-syntax/rsd-engyon-syntax.xml[Metanorma XML]
* https://riboseinc.github.io/rsd-engyon-syntax/rsd-engyon-syntax.rxl[Relaton XML (Bibliographic item)]

Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://github.com/riboseinc/rsd-engyon-syntax/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* RSD XML (https://github.com/riboseinc/metanorma-model-rsd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open rsd-*.html
----

