[[syntax]]
== Engyon Protected Text

Engyon Protected Text (EPT) is a human-editable annotation method that allows a text format document to contain finely grained cryptographic confidentiality and integrity features. It allows parties with different access parameters (e.g. clearance) to collaboratively work on the same document.

EPT annotation is contained in comments so that it does not affect rendering or compilation of the document.

* *Classified* sections are encrypted if the document is in _unclassified state_. 
 
* *Signed* sections are protected by a signature and can't be modified without detection. 

An initial non-integrated version of Engyon "protect" tools takes a form of a single-pass parser that allows a text-format documents to be reversibly transformed between different classification levels. The same tool can also be used to verify and create signatures inside the document.

In practice this allows a (partly or wholly) unclassified version of a document to be automatically created where restricted parts are replaced with invisible references (or with full encrypted blocks) for distribution. Vice versa, one can _reclassify_  a modified unclassified document, making confidential parts in the document available and editable again. Signatures are verified and updated with the same tool.

Note that the EPT markup can be used in all parts of the document and across different document types, including metadata. An unclassified version of a document doesn't have to include the authors of its classified portions, for example. Furthermore it is possible to construct a browser plugin that unlocks confidential portions of, say, a HTML document with a secret key.


=== EPT Statement

An EPT statement is enclosed by a left separator `LEFT_SEP` and right separator `RIGHT_SEP`, so that the EPT statement itself appears as
----
  <( STATEMENT )> 
----
in the editable text. The annotation can use the comments feature of a host language so that these markings do not affect the rendering or compilation of the document. Some examples:

|===
| Format 				| `LEFT_SEP`	 	| `RIGHT_SEP` 

| Raw text format		| `"\n<("`,     	| `")>"`
| AsciiDoc and C++,		| `"\n// <("`	  	| `")>"`
| MarkDown, XML, HTML	| `"<-- <("`		| `")> -->"`
| (La)TeX and similar	| `"\n% <("`		| `")>"`
|===


The separators are configurable and are determined from file type (extension), if available. The statements are mostly intended to be on their own line, hence the newline (`'\n'`) in `LEFT_SEP`.

Such statements define blocks of text (such as a confidential or signed part). Blocks can include other blocks for multi-level access control and/or integrity protection.


=== Immutable Blocks and Binary Blobs

EPT supports Content Addressed Storage (CAS) to abbreviate documents for editing and transmission. CAS allows non-changing parts of a document to be referred by their contents. We use this system primarily for ciphertext and signature data, but it can be used for arbitrary purposes; for example to include a well known public piece of text such as a standard license agreement.

All references within an EPT are fully unambiguous -- the reference alone fully specifies what is being referenced. Therefore there cannot be an EPT reference by the contents of a filename or a web address. This is needed to guarantee that signatures are well defined. It is always possible to "open up" an EPT document (up to the viewers' access level anyway.)

There is a helper notation which does not offer direct cryptographic confidentiality or integrity protection, but still helps to avoid accidental changes to static parts of a document. This is accomplished by enclosing them in an IMMUTABLE / MUTABLE block construct.
----
// <( IMMUTABLE Approved-May )>
(c) 2018 Ribose Inc. Any trade name used in this document .. 
// <( MUTABLE Approved-May )>
----

When ran through the parser with appropriate parameters the contents of the block marked `"Approved-May"` can be hidden from view and replaced by a simple object reference to the hash of its "muted" contents:
----
// <( MUTED Approved-May sha384=DC910F5E499F8BE84488D.. )>
----
Often such blobs are stored in local object storage, e.g. a directory with files whose filenames match with a hexadecimal hash of their contents. Such objects can also be shared via a cloud service or using peer-to-peer methods. Content addressed storage implies nothing about the storage or transport technologies used to fetch an object.

If classified segment is muted, it is stored in ciphertext form. 


=== Group keys

Engyon supports both very simple and highly advanced key management features, such as:

* A secret key derived from a passphrase with a key derivation function such as Argon2.

* An access-restricted local secret key file to allow automated processing.

* SmartCards and Hardware Security Modules (HSMs).

* An online key server or identity provider mechanism such as SAML. This allows access control lists to be centrally managed within an organization.

* Timed declassification where a trusted third party notary service is used to automatically declassify a document at certain time.

* k-of-n group control where "k" members of an n-member group are required to decrypt or sign document -- e.g. two persons with given security classification.

Due to the wide spectrum of potential key management methods, a "key" actually refers to a configuration information that specifies how a specific key can be obtained and used. This configuration is specified in Nereon configuration syntax (NOC), which is close to nginx UCL and JSON. 

Within the EPT syntax, a shorthand syntax is used for keys. Again, a reference is made to the the contents of the key file of structure. The actual key storage and access is left to the implementation.

Keys must be defined before they are used so typically they are defined in a signed block at the beginning of the document.
----
// <( SIGNED ... )>
// <( KEY Deputies sha384=86716A025E4AAF0347C9.. )>
// <( CERT Alice sha384=7725AD485A8EBDE97BB04E86C1.. )>
  .. document body ..
// <( UNKEY Deputies )>
// <( SIGNATURE .. )>
----
Defines that the hash of the key file for "Deputies" classification group and the public key certificate for "Alice" that can be used to verify her signatures. 

Keys configuration files can be also included in the document itself in base64 format:
----
// <( KEY Deputies base64=86716A025E4AAF0347C9.. )>
----
This of course makes no sense unless the key format uses e.g. passphrase protection.

A key shorthand does not need to be globally unique; we may use UNKEY and UNCERT statements that cause the parser to forget the reference to a given secret or public key name.


=== Classified Blocks

A block of text can be marked as needing confidentiality protection if it is enclosed between CLASSIFY and UNCLASSIFY statements. Such statements also contain a short name of a shared confidentiality group. A confidentiality group name maps to a context-specific secret symmetric key. 

In this example a short text is classified to the "Deputies" group. This is the classified version of the block.
----
// <( CLASSIFY Deputies aes256siv )> 
Confidential Source 13 is Mallory.
// <( UNCLASSIFY Deputies )>
----
The third parameter in a CLASSIFY statement is the preferred algorithm to be used, e.g. "aes256siv" for AES-256 in SIV mode.

When the document is unclassified (i.e. the protect tool is ran on it), the CLASSIFY / UNCLASSIFY block is encrypted with the group key "Deputies". Its contents are replaced by a single CLASSIFIED statement, name of the same group key and either the a base64 representation of the ciphertext or a hash reference to it.
----
//  <( CLASSIFIED Deputies aes256siv:base64=0mlH0RxyPOf8b1r.. )> 
----
Since an authenticated encryption algorithm is used, any modification to the corciphertext will be detected (


or if a hash reference is used,
----
//  <( CLASSIFIED Deputies aes256siv:sha384=DC910F5E499F8B... )> 
----

In practice the hash references are used when distributing the unclassified version to parties who do not have access to the classified information. Conversely, full ciphertext can be included in versions that are distributed to parties that can decrypt the classified data. In both cases the result can be handled as an unclassified document (if contains CLASSIFIED statements instead of CLASSIFY / UNCLASSIFY statements).

The storage of the encrypted blobs is left to the implementation, but they can be simply put in an "objects" folder of current working directory, with the hash as a filename. However this storage does not have to be permanent -- the encrypted objects needed for reclassifying a document after edits have been made to its unclassified form can be extracted from an older classified version of the same document.


=== Signed (integrity-protected) blocks

Blocks that are are integrity protected are limited by SIGNED / SIGNATURE statements. 
----
// <( SIGNED Alice ecdsap384 )>
A reward of $3.14 is offered for information leading to arrest of Bob.
// <( SIGNATURE Alice ecdsap384:base64=fI3m+vgcovG1Olu31WPVyh.. )>
----

Alternatively to the signature itself being contained in the document, a hash reference may be used here too.
----
// <( SIGNED Bob ecdsap384 )>
Eve did it, she is Evil.
// <( SIGNATURE Bob ecdsap384:sha384=C1A2D3E33CC6928BE5CD.. )>
----

Signature blocks can be inside or outside of classified blocks, allowing classified signatures and signature verification of mixed unclassified / classified data. Also signing a muted block allows a detached signature to be generated:
----
<( SIGNED Carol ecdsap384 )>
<( MUTED sha384=A206AD1D11C61BE8B5423DCBE.. )>
<( SIGNATURE Carol ecdsap384:sha384=C1A2D3E33CC6928BE5CD.. )>
----

For purposes of computing the signature hash, all MUTABLE and CLASSIFIED blocks are replaced by their hashed content representation (`<( CLASSIFIED name alg=01234.. 0)`). This may or may not require encryption but allows the signature the same signature to be valid for both classified and unclassified versions of the document.



=== Cryptographic Realization

We will adopt a flexible approach to cryptographic core algorithms, with an emphasis on international and national standard algorithms. For symmetric cryptography this means block ciphers AES, SM4, Kuznyechik [GOST R 34.12-2015], for hash functions SHA, SM3, and Streebog [GOST R 34.11-2012]. For asymmetric primitives similar national algorithms exist. 

A baseline set of supported default algorithms is defined, consisting of AES-256, SHA2-384, ECDSA P-384, and RSA with 3072-bit key. This corresponds to the technical requirements for American TOP SECRET classification in current CNSA suite defined in CNSSP 15 "Use of Public Standards for Secure Information Sharing" ( October 20, 2016 ). See: https://www.iad.gov/iad/programs/iad-initiatives/cnsa-suite.cfm (Requires accepting a funny DoD certificate.)

It is desirable that the cryptographic transformations are completely deterministic,  so that the same input text will always yield the same ciphertext and therefore the same ciphertext hash. This is not a requirement in all of the above mentioned standards, but with appropriate mode selection and deterministic random number generation this should be achievable.


==== Symmetric Authenticated Encryption

It may be desirable to use a standardized lossless compression technique such as DEFLATE [RFC 1951] to compress text sections before encryption.

Due to its minimal message expansion and non-sequential nature of data being encrypted, a nonce-reuse/misuse resistant Authenticated Encryption with Associated Data (AEAD) mechanism seems to be a good choice for Engyon. Such modes are necessarily "double-pass" modes (for the encrypted blocks) but we envision that even in streaming mode this does not impose a large memory requirement due to hierarchical nature of the operation.

A natural choice is to use a block cipher (e.g. AES-256) in SIV (Synthetic Initialization Vector) mode [RFC5297]. A SIV ciphertext is always 16 bytes larger than plaintext and the 16-byte authentication tag also serves as the "synthetic IV". 

The SIV mode allows use of associated authenticated data, which may be used to establish context in order to restrict the way confidential sections can be moved in relationship to each other and between documents. However we leave that to later specification.


==== Signatures 

Similarly a deterministic signature function is used so that a matching signature is always generated if the text is unmodified. An simple choice is the deterministic variant of ECDSA [RFC 6979]. 

Signature functions that rely on randomness may be turned into deterministic algorithms in similar fashion as in RFC 6979, by using a hash of the signed data as a seed for random number generation. There are arguments why this is often more secure than purely random seeding. Furthermore the random seed cannot be used as a secret information transmission channel. In any case, the deterministic randomness generation does not usually effect signature verification (e.g. deterministic ECDSA RFC6979 signatures can be verified like any other ECDSA signature).


